### ISSUE TITLE
register 위치 수정

### ISSUE THREAD

**Issue by cofls980** [Introversion-Relay-Chat/ft_irc#39]
> pass
> :tmp.server.name 461 * PASS :Not enough parameters
> time
> :tmp.server.name 391 * tmp.server.name :Tue Dec 13 02:09:20 2022

위 예시와 같이 pass 명령어만 잘못 입력하였을 때 등록 상태로 바뀌어 버리는 오류 해결하겠습니다.

**Comment by dbin67** [comment]
간단한 수정이기에 바로 머지했습니다.
