### ISSUE TITLE
[BUG] LIST 명령어 수행 시 Segmentation fault 오류 발생

### ISSUE THREAD

**Issue by sichoi42** [Introversion-Relay-Chat/ft_irc#48]
## 에러 발생 조건
```
pass pass
nick sichoi
user sichoi 0 * :42 Seoul
invite test #test
list
```
위 명령어를 순서대로 입력시 Segmentation fault가 발생합니다.

## 에러 발생 원인

```
Channel *Server::getChannelByName(std::string channel_name) {
	return _channels[channel_name];
}
```
원인은 `Server::_channels` 멤버 변수의 자료형이 `map`이기 때문에 생긴 것으로 보입니다.
`Server::getChannelByName`함수에서 인자로 들어온 `channel_name`을 단순히 `_channels`에서 찾아 return하는 방식인데,
`map` 자료형은 존재하지 않는 키로 접근하면, 해당 키 값을 새로 추가하는 방식이기 때문입니다.

`Server::getChannelByName`에서 `channel_name`으로 test라는 존재하지 않는 채널이 들어올 때 key가 test인 pair 하나를 추가합니다.

```
// RPL_LISTSTART
sender->getServer()->sendMsg(join(sender_prefix, "321", target, RPL_LISTSTART()), sender);
for (unsigned long i=0; i < channels.size(); i++){
	std::cout << i << std::endl;
	channel = sender->getServer()->getChannelByName(channels[i]);
	visible = toString(channel->getVisibleUsers(sender));
	topic = channel->getTopic();
        ...
}
```
이제 LIST 함수에서 서버에 존재하는 채널을 `getChannelByName()`를 통해 가져오게 되면, test라는 이름의 key에 해당하는 값 `Channel *`는 메모리를 할당받지 않았기 때문에 `getVisibleUsers()`로 접근 시 Segmentation fault가 발생합니다.

## 해결 방안
```
user = sender->getServer()->getUserByName(message.middle[0]);
channel = sender->getServer()->getChannelByName(message.middle[1]);
```
LIST 함수에서 이런식으로 `getUserByName`와 `getChannelByName`를 통해 유저와 채널 정보를 얻어올 때 `std::map::find`를 이용하면 존재하지 않는 값이 생성되는 일을 막을 수 있을 것 같습니다..!

**Comment by dbin67** [comment]
제가 c++ map에 대해 이해가 부족했던것 같습니다.
Server.cpp 에서 getChannelByName 메소드를 수정하면 될 것 같습니다.
마찬가지의 이유로 getUserByFd 메소드도 수정하겠습니다.

**Comment by dbin67** [comment]
추가로 getUserByName 은 []연산자가 사용되지 않았기에 문제없을 것 같습니다.
