### ISSUE TITLE
NAMES 결과로 나오는 목록의 마지막 출력 부분

### ISSUE THREAD

**Issue by cofls980** [Introversion-Relay-Chat/ft_irc#50]
[RFC]
> At the end of this list, a list of users who are visible but either not on any channel or not on a visible channel are listed as being on ‘channel’ "*".
> => 모든 채널에 대해 반환한 후,  볼 수 있는 유저 중에 아무채널에도 속해있지 않거나 속해 있는 모든 채널이 sender가 볼 수 없는 경우channel * : userlist 로 반환합니다.

[TEST]

> pass pass
> nick one
> user two three a :a
> join #aaa 
> :tmp.server.name 331 one #aaa :No topic is set
> :tmp.server.name 353 one #aaa :@one 
> names #aaa
> :tmp.server.name 353 one #aaa :@one 
> :tmp.server.name 366 one #aaa :End of /NAMES list
> :tmp.server.name 353 one * :one 
> :tmp.server.name 366 one * :End of /NAMES list

rfc에 나와있는 NAMES명령어 설명을 생각하면서 NAMES 명령을 테스트 했을 때
> :tmp.server.name 353 one * :one 
> :tmp.server.name 366 one * :End of /NAMES list

마지막으로 나오는 이 응답은 one이 #aaa채널에 속해 있어서 출력되면 안된다고 생각하는데 제가 생각한게 맞나요??

**Comment by dbin67** [comment]
나오면 안되는게 맞고 NAMES 48번째줄에
```
user_channels = user->getJoinedChannels();
// pass if user unvisible or on any channel
if ((user->getMode() & FLAG_USER_I) || !user_channels.empty()) {
    continue ;
}
```
이렇게 조건도 걸어줬는데.. 왜 뜨는걸까요?

**Comment by cofls980** [comment]
```
server_users = sender->getServer()->getUsers();
userlist = std::string();
for (std::map<int, User *>::iterator it=server_users.begin(); it!=server_users.end(); it++) {
  user = (*it).second;
  // 유저가 어떠한 채널에 속해 있지 않거나 속해는 있지만 그 채널이 보이지 않는 경우
  if (user->getMode() & FLAG_USER_I) {
	  continue;
  }
  user_channels = user->getJoinedChannels();
  if (user_channels.empty()) {
	  userlist += user->getNickname() + " ";
  } else {
	  user_channels = user->getJoinedChannels();
	  for (chan_it=user_channels.begin(); chan_it!=user_channels.end(); chan_it++) {
		  if (!channel->checkVisible(sender)) {
			  userlist += user->getNickname() + " ";
		  }
	  }
  }
}
```

이렇게 고치는 게 맞을 것 같은데 어떻게 생각하시나요?

위 코드처럼 고치면 아래와 같은 결과가 나옵니다.

> pass pass
> nick one
> user two three a :a
> join #aaa
> :tmp.server.name 331 one #aaa :No topic is set
> :tmp.server.name 353 one #aaa :@one 
> names #aaa
> :tmp.server.name 353 one #aaa :@one 
> :tmp.server.name 366 one #aaa :End of /NAMES list
> :tmp.server.name 353 one * :
> :tmp.server.name 366 one * :End of /NAMES list

**Comment by dbin67** [comment]
아!! 46번째 줄에서 user_channels = user->getJoinedChannels(); 로 받아오는데
이걸 받기전에 42번째 줄에서
```
if (user->getMode() & FLAG_USER_I || !user_channels.empty()) {
	continue ;
}
```
이걸 사용했네요;; 코드 정리하면서 위치를 잘못옮긴듯합니다. 46번째줄을 위로 올리면 될 것 같은데요?

**Comment by cofls980** [comment]
그렇네요!
근데 if문에 !user_channels.empty()가 있으면 만약 유저가 private이나 secret채널에 있는 경우에 그냥 건너뛰게 되는데 이부분도 수정해야하는 것 맞죠?

**Comment by dbin67** [comment]
수정해주신 코드 읽어보았는데
만약 어떤 유저가 여러개의 private이나 secret채널에 있는 경우라면
userlist에 중복적으로 여러번 들어가게 될 것 같습니다

**Comment by cofls980** [comment]
그렇다면 break추가해서 아래와 같이 수정하면 해결될까요??
```
user = (*it).second;
if (user->getMode() & FLAG_USER_I) {
	continue ;
}
user_channels = user->getJoinedChannels();
if (user_channels.empty()) {
	userlist += user->getNickname() + " ";
} else {
	user_channels = user->getJoinedChannels();
	for (chan_it=user_channels.begin(); chan_it!=user_channels.end(); chan_it++) {
		if (!channel->checkVisible(sender)) {
			userlist += user->getNickname() + " ";
			break;
		}
	}
}
```

**Comment by dbin67** [comment]
아래처럼 수정하는게 맞지 않을까요?
```
for (std::map<int, User *>::iterator it=server_users.begin(); it!=server_users.end(); it++) {
        user = (*it).second;
	user_channels = user->getJoinedChannels();
	if (user->getMode() & FLAG_USER_I) {
		continue ;
	}
	if (!user_channels.empty()) {
		for (chan_it=user_channels.begin(); chan_it!=user_channels.end(); chan_it++) {
			channel = sender->getServer()->getChannelByName(*chan_it);
			if (channel->checkVisible(sender)) {
				continue ;
			}
			break ;
		}
		if (chan_it != user_channels.end()) {
			continue;
		}
	}
	userlist += user->getNickname() + " ";
}
```

**Comment by cofls980** [comment]
그렇네요! 그럼 위 코드로 수정해서 푸시하도록 하겠습니다!

**Comment by dbin67** [comment]
2번째로 수정해주신 코드도 문제가
한 개의 private 채널과 여러개 public 채널에 들어가있는 경우가 문제가 될 것 같습니다
